spring.application.name=HoneyCart
server.port=9090

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/honey_cart}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:Thar2030}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=HoneyCart@2025#SecureKey$TestMode!ProjectByDev@9090&MySQL#JWT512BitLongSecretKeyForHoneyCartApplication

# --- UPDATED CORS CONFIGURATION ---
spring.web.cors.allowed-origin-patterns=http://localhost:5173,https://honeycart-frontend.onrender.com
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Content-Type,Authorization
spring.web.cors.allow-credentials=true
spring.web.cors.exposed-headers=*
# ----------------------------------

razorpay.key_id=rzp_test_SMFhtMnapw3aPc
razorpay.key_secret=y9Nd6YQ7waQbVbsD4z6H6vIr

spring.datasource.hikari.maximum-pool-size=3